# -*- coding: utf-8 -*-
"""Open cv for video processing.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16LxRDLakEMoBYZbhpmm8gAhHG_TErhyR
"""

pip install twilio
 from logging import WARNING
#import opencv library
import cv2
#import numpy
import numpy as np
#import image function from keras
from keras.preprocessing import image
#import load_model from keras
from keras.models import load_model
#import client from twilio API
from twilio.rest import Client
#import playsound package